name: PCFly
main: Angel\PCFly\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 2.1.1
author: Angel
commands:
  fly:
    description: "/fly command!"
permissions:
  fly.command:
    default: false
